name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --check --write .
        continue-on-error: true

      - name: Run ESLint
        run: npx eslint .
        continue-on-error: true

      # - name: Deploy to DigitalOcean App Platform
      #   uses: digitalocean/app_action@v1.1.5
      #   with:
      #     app_name: ${{ secrets.DO_APP_NAME }}
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        