name: Reset Special Missions

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
  # Optional: trigger on push to test the script
  push:
    branches:
      - main
      - dev
    paths:
      - 'scripts/cron-job-special-mission.js'
      - '.github/workflows/reset-specialMission.yml'

jobs:
  reset-special-missions:
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run special missions reset
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: production
        run: node scripts/cron-job-special-mission.js